version: '3.7'

services:
  web:
    build: ./django_server
    command: gunicorn tally_counter.wsgi:application --bind 0.0.0.0:28001
    ports:
      - 28001:28001
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - ./django_server:/app

  db:
    image: postgres:12.1
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5433:5433

  react:
    build: ./react_ui
    command: "yarn; yarn build"
    volumes:
      - ./react_ui/build:/app/build
      - ./react_ui/src:/app/src
